"""Alembic revision script.

This file was generated by async-zulip-bot-sdk's Alembic template.

${message if message else ""}
"""

from __future__ import annotations

from typing import Optional, Sequence

from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic.
revision: str = "${up_revision}"
down_revision: Optional[str] = ${repr(down_revision)}
branch_labels: Optional[Sequence[str]] = ${repr(branch_labels)}
depends_on: Optional[str] = ${repr(depends_on)}


def upgrade() -> None:
    """Apply schema changes for this revision."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Revert schema changes for this revision."""
    ${downgrades if downgrades else "pass"}
